export const RtkqTagEnum = {
	AUTH_USER: "AUTH_USER",
	USERS: "USERS",
	ADMIN_LIST: "ADMIN_LIST",
	WORKSPACE: "WORKSPACE",
	WORKSPACE_USERS: "WORKSPACE_USERS",
	ORGANIZATIION_USERS: "ORGANIZATIION_USERS",
	ORGANIZATION: "ORGANIZATION",
	MEETINGS: "MEETINGS",
	MEETINGS_ATTENDEES: "MEETINGS_ATTENDEES",
};

// export enum RtkqTagEnum {
//   AUTH_USER = "AUTH_USER",
// }
